Feature/fix policy class hierarchy
smn-ailab/pymab pull request #1
Opened 2019-02-11 23:36 UTC by usaito

- policy moduleでクラスの継承関係が複雑だったのを簡略化しました
     - 正確には, context-free (stochastic) と contextual bandit policyそれぞれに対応する抽象基底クラスを一つづつ用意し, 全てのpolicyはそれらを親クラスとして持つようにしました.
- その他に, 変数名やメソッド名をスライドに合わせて変更しています. 

（まとめてcommitしてしまったのでレビューしにくいかもしれません. 申し訳ないです. 適宜お声がけください.）

2019-02-15 04:56 UTC, hasoya requested changes
数式やif文などもう少しコメントつけてくれると読みやすいです。

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/stochastic.py
> +        result = np.random.randint(self.n_actions)
気持ちの問題なんですが、

```python 
if np.random.rand() > self.epsilon:
    return np.argmax(self.estimated_rewards_temp)
else:
    return np.random.randint(self.n_actions)
```

と書いてしまった方が、不必要なときに`randint`を計算せずに済みますし、閾値を超えたら一番いいやつ、超えなかったらランダムという気持ちが伝わりやすいです。

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/stochastic.py
> +        self.estimated_rewards_temp = np.zeros(self.n_actions)
`temp`と書かれても具体的にどんなことをする変数かよくわからないです

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/stochastic.py
> +        self.data_size += 1
`num_epoch` ？

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/stochastic.py
> +        if self.data_size % self.batch_size == 0:
以前説明してくださった記憶もあるんですが、ここの意図ってどういうものでしょう

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/stochastic.py
> +        if self.data_size % self.batch_size == 0:
tempを一定間隔に更新するってことの目的がよくわからず

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/stochastic.py
> +        self.data_size += 1
もしくは `num_iter` ?

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/stochastic.py
> +        self.estimated_rewards_temp = np.zeros(self.n_actions)
あと、`temp`ならそれが外から見えたりいじったりできるpublic変数なのもカプセル化の考え方からしてすごく良くないです

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/stochastic.py
>  """This Module contains Stochastic Bandit Policies."""
参考にしたページとかあるならリンクかレファレンスでも貼っておいたら？

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/stochastic.py
> +        z = np.sum(np.exp(self.estimated_rewards_temp) / self.tau)
あと、rewardに対して`exp`取るとrewardが大きいときにinfinityになって死ぬのでこちらを参考に

https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/stochastic.py
> +        if 0 in self.action_counts:
意図をきちんとコメントで説明しましょう。

2019-02-15 04:56 UTC, hasoya commented on pymab/policy/contextual.py
> +        self.A_inv[action] -= self.A_inv[action] @ x @ x.T @ self.A_inv[action] / (1 + x.T @ self.A_inv[action] @ x)  # d * d
数式ごちゃごちゃ書くときは必ずコメントで元の数式を表現しておくと、ミスの防止にもつながりますし、可読性も高まります

2019-02-15 06:44 UTC, usaito commented on pymab/policy/stochastic.py
> +        if self.data_size % self.batch_size == 0:
問題によるのですが、報酬の情報が例えば100回に1回バッチで観測されるような設定に対応する意図があります。以前SMNで使っているMFは（一回一回の観測ごとに学習し直すのは不可能なので）1日に一回学習し直していると言った話を聞いた覚えがありますが、そのようなイメージです。

2019-02-15 06:52 UTC, hasoya commented on pymab/policy/stochastic.py
> +        if self.data_size % self.batch_size == 0:
なるほど

それなら、 `batch_size` -> `observation_interval`, `estimated_rewards_temp` -> `observed_rewards` とかの方がわかりやすくないですか？

2019-02-15 06:55 UTC, usaito commented on pymab/policy/stochastic.py
> +        if self.data_size % self.batch_size == 0:
確かにそうですね、あまり考慮せず変数名をつけてしまっていました。修正します。

2019-02-15 07:01 UTC, usaito commented on pymab/policy/stochastic.py
> +        self.estimated_rewards_temp = np.zeros(self.n_actions)
変数名を変えた上で、private変数にするイメージでしょうか？

2019-02-15 07:05 UTC, hasoya commented on pymab/policy/stochastic.py
> +        self.estimated_rewards_temp = np.zeros(self.n_actions)
いや、先ほどの話だと、これが外部から観測できるrewardなのでこちらはpublicであるべきかと思います。estimatedの方は利用方法によるかな…

2019-02-15 07:08 UTC, usaito commented on pymab/policy/stochastic.py
> +        self.estimated_rewards_temp = np.zeros(self.n_actions)
時点時点の報酬の推定値を利用する場面があるかどうかですか...？
ちょっと自分の方で考えてみます

2019-02-15 07:12 UTC, hasoya commented on pymab/policy/stochastic.py
> +        self.estimated_rewards_temp = np.zeros(self.n_actions)
そうですね。一旦publicにしてみて実際使いながら考えるでもいいと思いますよ

2019-02-18 01:09 UTC, usaito commented
ご指摘いただいた点（主にコメントや変数名）を修正しました。

2019-02-20 01:01 UTC, hasoya approved these changes
1箇所だけコメントつけました。このままで良いと思うなら、Mergeしちゃってください。

2019-02-20 01:01 UTC, hasoya commented on pymab/policy/contextual.py
> +    [1] 本多淳也, 中村篤祥. "バンディット問題の理論とアルゴリズム" 講談社 機械学習プロフェッショナルシリーズ, 2016.
広く使ってもらうなら、文献は英語の方がいいんでね？

2019-02-20 01:01 UTC, hasoya commented on pymab/policy/contextual.py
> +    [1] 本多淳也, 中村篤祥. "バンディット問題の理論とアルゴリズム" 講談社 機械学習プロフェッショナルシリーズ, 2016.
version 1通したら、ぼくらも英語に切り替えましょう。

2019-02-20 02:29 UTC, merged